### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by sosoeun** [dus532/softcone-blog-app#1]
시청자 통계 잘보고 있습니다.

방송인들간의 비교 기능과 평청자 한달~일년치를 한번에 볼 수 있는 그래프도 있으면 좋겠습니다. 방제랑 카테변경까지 보이는 건 아주 좋더라구여 화이팅하세여

**Comment by dus532** [comment]
와! 감사합니다! 아직 데이터가 1달이 안되서 ㅠㅠ 데이터가 쌓이면 좀더 준비해보겠습니다!
